### ISSUE TITLE
[한글로 문서화하기]  작업 범위 알림 _ word-cloud 블로그

### ISSUE THREAD

**Issue by heesungkim010** [20-1-SKKU-OSS/2020-1-OSS-5#18]
https://peekaboo-vision.blogspot.com/2012/11/a-wordcloud-in-python.html
위의 word-cloud 블로그  6번째 문단 내용까지 한글 문서화하겠습니다.
맨 위부터 코드 있는 부분 중 counts = counts/ float(counts.max())  여기까지입니다.

**Comment by jb0307** [comment]
확인했습니다.

**Comment by HACore** [comment]
확인했습니다.

**Comment by heesungkim010** [comment]
이 부분 작업 완료해서 이슈 닫습니다.
