### ISSUE TITLE
[한글로 문서화하기] 작업 방식에 관하여 의견구함

### ISSUE THREAD

**Issue by heesungkim010** [20-1-SKKU-OSS/2020-1-OSS-5#19]
각자 범위를 정해서 작업하기로 했는데요.
일단 각자 작업한 범위에 해당하는 post를 gh-pages에 따로따로 올리고, 
이후에 jekyll 에서 date 수정하는 식으로 해서 정적페이지에서 포스트 순서를 조정하면 어떨까 싶습니다.

어떠신가요?? 혹시 다른 방법이 있을까요?

**Comment by davidshyn1** [comment]
네 괜찮은 것같습니다.

**Comment by jb0307** [comment]
포스트 순서 맞추려면 말씀하신대로 마지막에 date조정해서 한번에 맞추고. 그 전까지는 순서 무시하고 포스트 작성 진행해도 될 것 같습니다. 아니면 카테고리 나눌 수 있거나 포스트 순서 지정할 수 있는 테마 찾아서 테마를 바꾸는 건 어떨까요? 괜찮은 테마 찾아볼게요

**Comment by heesungkim010** [comment]
카테고리 나눌수 있으먼 좋을거같습니다. 지금 테마에서는 카테고리는 못 나누는건가요??

**Comment by HACore** [comment]
사용자들이 보기 쉽고 사용하기 편하도록 돕는 게 문서화의 목적이니 카테고리화 할 수 있다면 하는 것이 좋을거 같습니다. 기존 테마에서 비슷하게 구성할 방법을 생각해보거나 새 테마를 찾아도 될거같아요.

**Comment by heesungkim010** [comment]
테마 변경으로 해결해서 이슈닫습니다.
