### ISSUE TITLE
Plural Issue에 대한 해결 방법

### ISSUE THREAD

**Issue by davidshyn1** [20-1-SKKU-OSS/2020-1-OSS-5#2]
wordcloud github 링크 #542를 참고하시면,
https://github.com/amueller/word_cloud/issues/542

원 프로젝트는 plural(복수) 형태인 단어를 모두 singular(단수) 형태로 normalise하는 것으로
normalise_plurals=True로 설정하여 진행하는데,

그렇게 하면, 'virus'같은 단어가 'viru'로 처리한다는 문제가 발생된다는 이슈가 있습니다.

복수 형태의 단어와 's'로 끝나는 단어를 정확히 구분해서 복수 형태의 단어는 단수로 바꿔주고, 's'로 끝나는 단어를 현 형태를 유지하는 코드를 구현하는 것도 좋은 해결방법일 것 같습니다.

**Comment by heesungkim010** [comment]
원 프로젝트에서의 issue는 사용자가 복수로 처리하지 말아야 할 단어들을 제공하면 그것들은 제외시킨다는 것 같은데요.
신성국님이 말씀하시는 건 사용자가 특정한 단어들을 제공하지 않은 상황에서도 normalization 과정에서 예외가 발생하지 않도록 구현해보자는 말씀이신가요?

**Comment by davidshyn1** [comment]
해당 이슈에 대해, 원 코드 작성자가 input을 미리 preprocessing하거나, generate_from_frequency 설정을 통해 해결하면 된다고 답변을 해주었는데, 이러한 단어들을 많이 포함한 긴 글의 경우, 코드 작성자가 준 solution이 명확하지 않은 것같아 해당 이슈를 가져왔습니다.

일단 해당 이슈를 코드를 수정하는 것으로 해결하자고 막연하게 생각하기만 해서, 구체적인 방법은 같이 해결하고자 했습니다.

김희성님께서 말씀하신 전자의 경우, 복수로 처리하지 말아야 할 단어들을 저희가 제공해서 제외하는 방식으로 해볼 수 있는 활동인 것 같네요.(물론, 's'로 끝나는 모든 단어를 다 제공할 순 없겠죠)
후자의 경우, English dictionary package 등의 패키지를 활용해야 할 것 같은데, 코드의 내용을 좀 더 공부해보고 가능한지 확인할 수 있을 것같아요.

**Comment by heesungkim010** [comment]
첫번째 경우에 대해서는 원 코드 작성자가 " I'm a bit worried about adding too many complex processing options. There's already so many options in WordCloud, it's very hard to keep track. " 라고 했는데요. 예외처리할 단어 리스트를 주더라도 단순한 조건 분기로는 예외처리 하기 힘들어서 저렇게 답변하지 않았나 싶네요. 좀더 자세히 봐보겠습니다.

그리고 두번째 경우에서는 pattern 라이브러리를 생각해봤는데요. 원 코드에서 normalize_plurals 과정에서는 끝자리가 s인거를 그냥 없애는데, 이때 pattern 라이브러리나 다른 것들을 사용하면 저희가 생각하는 대로 구현할 수 있지 않을까 생각합니다. 다만 실행시간이 너무 길어지지 않을까 하는 점이 걱정되긴 하네요.

**Comment by davidshyn1** [comment]
혹시 다른 분의 의견은 어떠신가요?
저희가 기간안에 해결할 수 있는 프로젝트라고 생각하시나요?

**Comment by HACore** [comment]
코드 내에서 normalise_plurals=True 시에 작동되는 흐름을 살펴봤는데, process_tokens 매서드를 보면 복수 형태의 단어를 단수 형태로 바꿨을때 그 단수 형태가 전체 텍스트에 존재하는 경우에만 normalise가 진행되도록 처리되어 있습니다.
즉 'virus'가 'viru'로 변해버리는 버그는 텍스트에 'viru'가 있기 때문에 발생하는 것으로 보입니다. 이는 실수 등으로 인한 텍스트 파일 자체의 문제이므로 사용자가 잘못된 단어를 수정해서 해결하는 방법이 word cloud의 효율을 유지할 수 있는 방법이지 않을까 싶습니다.

만약 이 현상을 애초에 발생하지 않도록 막으려면, 실행시간이 좀 길어질 수 있을 것 같긴 하지만,  신성국님이 언급해주신 English dictionary package 등을 이용해서 단수형태로 처리한 단어가 사전에 존재하는지 체크한 뒤 다음단계로 넘어가도록 하면 해결될 것 같습니다. (https://github.com/20-1-SKKU-OSS/2020-1-OSS-5/blob/f7e71b2b1f9533bef0b25159b5e3764c3a25ccbc/word_cloud/wordcloud/tokenization.py#L115)

**Comment by HACore** [comment]
해당 이슈가 해결되었으므로 이슈 닫겠습니다.
