### ISSUE TITLE
[한글로 문서화하기] 작업 범위 알림 _ word-cloud website

### ISSUE THREAD

**Issue by jb0307** [20-1-SKKU-OSS/2020-1-OSS-5#21]
http://amueller.github.io/word_cloud/cli.html
command line interface랑 named arguments 부분 한글문서화 진행하겠습니다.

**Comment by HACore** [comment]
확인했습니다.

**Comment by jb0307** [comment]
팀 프로젝트페이지에 포스트 올렸습니다.
