### ISSUE TITLE
[한글기능구현] input을 text가 아닌 list로 받을 시 문제점

### ISSUE THREAD

**Issue by davidshyn1** [20-1-SKKU-OSS/2020-1-OSS-5#29]
원 프로젝트의 코드를 리뷰하면서 확인한 점 중 하나가

input을 text파일이 아닌 list로 받을 경우,
해당 프로그램 실행 시 단어가 두 번 duplicate 되어 반영된다는 주석을 확인하였습니다.

저희 팀 코드의 경우, text file을 한글 자연어처리를 한 후 list로 저장해서 입력하기 때문에,
해당 문제에 대한 원 코드작성자의 solution에 따라
collocations=false 설정을 추가하겠습니다.

**Comment by davidshyn1** [comment]
해당 issue를 반영하여 pull-request 합니다.

**Comment by heesungkim010** [comment]
저희가 input을 string으로 하는데 string도 list처럼 중복된다는 내용인가요??

**Comment by davidshyn1** [comment]
제가 string을 list로 착각했네요 string의 경우는 collocations = True로 해야 될 것같아요
