### ISSUE TITLE
Gallery of Examples 브랜치 수정요청

### ISSUE THREAD

**Issue by jb0307** [20-1-SKKU-OSS/2020-1-OSS-5#36]
master에 커밋하셔서 정적페이지에 gallery of example 포스트 반영이 안되는 것 같습니다. pull request 번거로우시면 간단하게 gh-pages 브랜치에도 같은 내용으로 커밋해주시면 될 것 같아요!

**Comment by 605s** [comment]
확인하였습니다.

**Comment by jb0307** [comment]
감사합니다!
