### ISSUE TITLE
정적페이지 지킬테마 변경관련 질문

### ISSUE THREAD

**Issue by jb0307** [20-1-SKKU-OSS/2020-1-OSS-5#44]
https://jb0307.github.io/2020-1-OSS-5/

카테고리도 추가해보려 했는데 좀 어렵네요... 차선책으로 개인페이지에 사용한 테마에 tag가 있어서 팀페이지 포크해서 적용해봤습니다. 확인부탁드립니다!

그리고 적용하게 되면 지킬 테마 관련 파일들은 gh-pages에만 있는게 보기 좋을 것 같은데 gh-pages에서 master로 pull-request 할 때 같이 안 옮겨지는 방법이 있을까요?

**Comment by davidshyn1** [comment]
전 괜찮을 것같습니다.
브랜치 관련해서는 저도 잘 모르겠네요..

**Comment by jb0307** [comment]
알겠습니다 일단 commit 다시 정리해서 pull-request하겠습니다.

**Comment by heesungkim010** [comment]
ㅌ

**Comment by heesungkim010** [comment]
git cherry-pick 을 쓰면 특정 commit 만 pull request 할수 있다고 하네요. 그런데 그렇게 되면 하나씩 고르는거라 조금 번거로울거 같긴 합니다..
 아니면 gh-pages브랜치에 있는 지킬테마 관련 파일을 한 폴더로 정리해서 넣어놓고 master 브랜치로 merge하는건 어떨까요?

**Comment by jb0307** [comment]
폴더위치랑 페이지랑 상관있는지 확인해보고 말씀드릴게요!

**Comment by jb0307** [comment]
gh-pages에서 한 폴더에 넣어두면 페이지가 안만들어지네요. gh-pages를 master로 merge한 다음에 master에서 정리하는 방식으로 해야할 것 같습니다!

**Comment by HACore** [comment]
gh-pages를 master로 merge하는 경우 발생하던 conflict 해결 후 master에서 한 폴더로 정리 완료했습니다.
