### ISSUE TITLE
plurals issue를 해결하기 위한 과정의 문제점

### ISSUE THREAD

**Issue by HACore** [20-1-SKKU-OSS/2020-1-OSS-5#49]
tokenization.py 내부의 process_tokens 메소드에서 복수형을 단수형의 frequency와 합친후 복수형을 제거하는 작업이 이뤄지는 것을 파악한 후
복수형 단어의 마지막 s철자를 삭제한 단어가 영어단어로 존재하는 경우에만 단수형의 frequency와 합치는 작업이 일어나도록 처리를 해봤습니다.
하지만 결과값에 변화가 없어 word cloud를 생성하는 전체 과정에서 이 메소드를 사용하는 부분을 다 살펴봤지만 잘 해결이 안되네요..

pull-request한 제 코드를 리뷰해주시고 어떤 부분이 문제인지 의견 주실 수 있으시면 감사하겠습니다.

**Comment by davidshyn1** [comment]
리뷰해보겠습니다.

**Comment by davidshyn1** [comment]
혹시 wordcloud 패키지를 pip install로 하셨나요?
이미 우리 repository에 wordcloud 폴더 내에 있는 tokenization.py를 수정하였기 때문에

pip install wordcloud을 통해 wordcloud를 설치한 경우, 수정된 코드가 아닌 기존 코드로 작동하게 됩니다.

제가 수정된 코드로 돌려봤는데
{viru: 1}, {virus: 1}라는 결과값이 나와 생각대로 잘 된 것 같습니다.

**Comment by davidshyn1** [comment]
import pyximport
pyximport.install()

from wordcloud import WordCloud
wc = WordCloud().process_text('viru virus')
print(wc)

이 코드로 실행보시면 될 것 같습니다.

**Comment by HACore** [comment]
실행 방식의 문제였군요..!
리뷰 감사합니다!
