### ISSUE TITLE
plural issue 실행방법

### ISSUE THREAD

**Issue by davidshyn1** [20-1-SKKU-OSS/2020-1-OSS-5#53]
Pycharm으로 실행하는 경우,
1. pip install wordcloud로 설치한 경우, uninstall합니다.
2. https://github.com/20-1-SKKU-OSS/2020-1-OSS-5/issues/49 에 나와있는 코드를 .py로 만듭니다.
3. ./word_cloud/wordcloud 폴더에 오른쪽 마우스->Mark directory as->Sources root를 클릭합니다
4. cython 패키지를 설치합니다.
5. 해당 .py를 실행합니다.

Anaconda로 실행하는 경우,
1. pip install wordcloud로 설치한 경우, uninstall합니다.
2. https://github.com/20-1-SKKU-OSS/2020-1-OSS-5/issues/49 에서의 코드를 .py로 만들어 ./word_cloud 디렉토리에 저장합니다
3. cython 패키지를 설치합니다.
4. 해당 .py를 실행합니다.

실행방법이 좀 복잡해서 여기에다 올립니다.

**Comment by HACore** [comment]
깔끔한 정리 감사합니다!
