### ISSUE TITLE
[한글로 문서화하기] 작업범위 알림 _word cloud blog

### ISSUE THREAD

**Issue by heesungkim010** [20-1-SKKU-OSS/2020-1-OSS-5#54]
https://peekaboo-vision.blogspot.com/2012/11/a-wordcloud-in-python.html

blog post의 The integral image is basically a 2d cumulative sum and can be computed as~ 까지 문서화하겠습니다.

**Comment by jb0307** [comment]
그 문장 바로 전까지만 해주시면 될 것 같아요!

**Comment by heesungkim010** [comment]
네 알겠습니다~

**Comment by heesungkim010** [comment]
작업완료하고 이슈닫습니다
