### ISSUE TITLE
정적페이지에 그림 삽입 문제

### ISSUE THREAD

**Issue by davidshyn1** [20-1-SKKU-OSS/2020-1-OSS-5#56]
https://20-1-skku-oss.github.io/2020-1-OSS-5/korean_ver/

제가 작성하고 있는 post인데
제가 넣은 그림들이 다 깨지네요.
혹시 해결 방법에 대해서 아시는 분이 있나요?

https://github.com/20-1-SKKU-OSS/2020-1-OSS-5/blob/gh-pages/_posts/2020-06-06-korean_ver.md
md파일입니다.

**Comment by HACore** [comment]
사진 파일의 경로가 저희팀 repo가 아니여서 문제가 생기는 것으로 추측됩니다.
팀repo에 이미지 저장 후 그 경로로 파일 위치를 지정해보시는게 좋을 것 같습니다!

**Comment by jb0307** [comment]
저도 포크해서 확인해보겠습니다

**Comment by jb0307** [comment]
파일명이 한글이라 그런것 같습니다 영어로 바꾸면 해결됩니다!
https://jb0307.github.io/2020-1-OSS-5/korean_ver/

**Comment by davidshyn1** [comment]
안정복님께서 구현하신 md파일 코드 보고 해결하였습니다. 감사합니다.
