### ISSUE TITLE
[한글기능구현] 정적페이지에서 tag 관련

### ISSUE THREAD

**Issue by heesungkim010** [20-1-SKKU-OSS/2020-1-OSS-5#66]
정적페이지에 tag 가보면 wiki / documentation  이렇게 구분돼있고, 한글기능 구현한 게 documentation에 들어가 있던데요.
아예 tag를 다른거 만들어서 거기에 넣는건 어떨까요? 괜찮으시면 제가 수정하겠습니다.

**Comment by davidshyn1** [comment]
한글 기능 구현은 따로 tag로 만들어놓으시는게 좋을 것같습니다.

**Comment by jb0307** [comment]
다른 포스트도 같이 분류하겠습니다.

**Comment by HACore** [comment]
네 기능 구현도 따로 분류하고 documentation도 블로그와 wordcloud 문서는 따로 분류하는 것이 좋을것 같아요!

**Comment by jb0307** [comment]
tag 나누고 merge했습니다!
