### ISSUE TITLE
Blog Post(1)에서 링크 활성화가 안 된 부분이 있습니다.

### ISSUE THREAD

**Issue by jb0307** [20-1-SKKU-OSS/2020-1-OSS-5#71]
맨 처음 "word_cloud의 [blog post][Blog]" 이 부분입니다. 링크 추가가 안되어 있는 것 같은데 확인부탁드릴게요! 그리고 blog post 두개 합치는게 좋을 것 같은데 blog post(2) 삭제하고 blog post(1)에 합치는 것도 혹시 같이 진행해주실 수 있으신가요?

**Comment by heesungkim010** [comment]
네 두가지 수정하겠습니다.

**Comment by heesungkim010** [comment]
수정해서 이슈 닫습니다.
